#pragma once

#include "raylib/raylib.h"

#define SPRITE_SIZE 8

typedef Rectangle SpriteImage;

#define SITELEN_A (Rectangle){ 0 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_AKESI (Rectangle){ 1 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ALA (Rectangle){ 2 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ALASA (Rectangle){ 3 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ALE (Rectangle){ 4 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ANPA (Rectangle){ 5 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ANTE (Rectangle){ 6 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ANU (Rectangle){ 7 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_AWEN (Rectangle){ 8 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_E (Rectangle){ 9 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_EN (Rectangle){ 10 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ESUN (Rectangle){ 11 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_IJO (Rectangle){ 12 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_IKE (Rectangle){ 13 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ILO (Rectangle){ 14 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_INSA (Rectangle){ 15 * SPRITE_SIZE, 0 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_JAKI (Rectangle){ 0 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_JAN (Rectangle){ 1 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_JELO (Rectangle){ 2 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_JO (Rectangle){ 3 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KALA (Rectangle){ 4 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KALAMA (Rectangle){ 5 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KAMA (Rectangle){ 6 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KASI (Rectangle){ 7 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KEN (Rectangle){ 8 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KEPEKEN (Rectangle){ 9 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KILI (Rectangle){ 10 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KIWEN (Rectangle){ 11 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KO (Rectangle){ 12 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KON (Rectangle){ 13 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KULE (Rectangle){ 14 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KULUPU (Rectangle){ 15 * SPRITE_SIZE, 1 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_KUTE (Rectangle){ 0 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LA (Rectangle){ 1 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LAPE (Rectangle){ 2 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LASO (Rectangle){ 3 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LAWA (Rectangle){ 4 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LEN (Rectangle){ 5 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LETE (Rectangle){ 6 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LI (Rectangle){ 7 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LILI (Rectangle){ 8 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LINJA (Rectangle){ 9 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LIPU (Rectangle){ 10 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LOJE (Rectangle){ 11 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LON (Rectangle){ 12 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LUKA (Rectangle){ 13 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LUKIN (Rectangle){ 14 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LUPA (Rectangle){ 15 * SPRITE_SIZE, 2 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_MA (Rectangle){ 0 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MAMA (Rectangle){ 1 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MANi (Rectangle){ 2 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MELI (Rectangle){ 3 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MI (Rectangle){ 4 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MIJE (Rectangle){ 5 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MOKU (Rectangle){ 6 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MOLI (Rectangle){ 7 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MONSI (Rectangle){ 8 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MU (Rectangle){ 9 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MUN (Rectangle){ 10 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MUSI (Rectangle){ 11 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MUTE (Rectangle){ 12 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_NANPA (Rectangle){ 13 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_NASA (Rectangle){ 14 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_NASIN (Rectangle){ 15 * SPRITE_SIZE, 3 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_NENA (Rectangle){ 0 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_NI (Rectangle){ 1 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_NIMI (Rectangle){ 2 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_NOKA (Rectangle){ 3 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_O (Rectangle){ 4 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_OLIN (Rectangle){ 5 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_ONA (Rectangle){ 6 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_OPEN (Rectangle){ 7 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PAKALA (Rectangle){ 8 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PALI (Rectangle){ 9 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PALISA (Rectangle){ 10 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PAN (Rectangle){ 11 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PANA (Rectangle){ 12 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PI (Rectangle){ 13 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PILIN (Rectangle){ 14 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PIMEJA (Rectangle){ 15 * SPRITE_SIZE, 4 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_PINI (Rectangle){ 0 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PIPI (Rectangle){ 1 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_POKA (Rectangle){ 2 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_POKI (Rectangle){ 3 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PONA (Rectangle){ 4 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_PU (Rectangle){ 5 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SAMA (Rectangle){ 6 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SELI (Rectangle){ 7 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SELO (Rectangle){ 8 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SEME (Rectangle){ 9 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SEWI (Rectangle){ 10 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SIJELO (Rectangle){ 11 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SIKE (Rectangle){ 12 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SIN (Rectangle){ 13 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SINA (Rectangle){ 14 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SINPIN (Rectangle){ 15 * SPRITE_SIZE, 5 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_SITELEN (Rectangle){ 0 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SONA (Rectangle){ 1 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SOWELI (Rectangle){ 2 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SULI (Rectangle){ 3 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SUNO (Rectangle){ 4 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SUPA (Rectangle){ 5 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_SUWI (Rectangle){ 6 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TAN (Rectangle){ 7 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TASO (Rectangle){ 8 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TAWA (Rectangle){ 9 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TELO (Rectangle){ 10 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TENPO (Rectangle){ 11 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TOKI (Rectangle){ 12 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TOMO (Rectangle){ 13 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TU (Rectangle){ 14 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_UNPA (Rectangle){ 15 * SPRITE_SIZE, 6 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_UTA (Rectangle){ 0 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_UTALA (Rectangle){ 1 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_WALO (Rectangle){ 2 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_WAN (Rectangle){ 3 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_WASO (Rectangle){ 4 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_WAWA (Rectangle){ 5 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_WEKA (Rectangle){ 6 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_WILE (Rectangle){ 7 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_EPIKU (Rectangle){ 8 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_JASIMA (Rectangle){ 9 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KIJETESANTAKALU (Rectangle){ 10 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KIN (Rectangle){ 11 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KIPISI (Rectangle){ 12 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KOKOSILA (Rectangle){ 13 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_KU (Rectangle){ 14 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_LANPAN (Rectangle){ 15 * SPRITE_SIZE, 7 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

#define SITELEN_LEKO (Rectangle){ 0 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MESO (Rectangle){ 1 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MISIKEKE (Rectangle){ 2 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_MONSUTA (Rectangle){ 3 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_N (Rectangle){ 4 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_NAMAKO (Rectangle){ 5 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_OKO (Rectangle){ 6 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }
#define SITELEN_TONSI (Rectangle){ 7 * SPRITE_SIZE, 8 * SPRITE_SIZE, SPRITE_SIZE, SPRITE_SIZE }

